# Dockerfile for local development - see docker-compose-dev.yml for usage instructions
FROM node:22

RUN apt-get update && DEBIAN_FRONTEND=noninteractive \
    apt-get install --no-install-recommends --assume-yes \
    curl wget micro htop less bash git

WORKDIR /app
RUN git config --global --add safe.directory /app
RUN npm install -g pnpm

EXPOSE 4000
